[package]
name = "xmtp-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
xmtp.workspace = true
k256.workspace = true
sha3.workspace = true
hex.workspace = true
getrandom.workspace = true

[lints]
workspace = true
