[package]
name = "xmtp-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
xmtp.workspace = true
k256 = { version = "0.13", features = ["ecdsa"] }
sha3 = "0.10"
hex = "0.4"
getrandom = "0.2"

[lints]
workspace = true
